SVM
Feature Extraction Method: GLCM
Features Taken with distance = 1,3,5, angle = 45,90 (total 25 features)

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
cd /content/drive/"MyDrive/Machine Learning/GLCM"

/content/drive/MyDrive/Machine Learning/GLCM


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import glob
import cv2
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix
import itertools
from skimage.filters import sobel
from skimage.feature import greycomatrix, greycoprops
import time

In [ ]:
X_train = list()
X_test = list()
y_train = list()
y_test = list()

# for k fold cross validation
x_new = list()
y_new = list()

In [ ]:
# 0 = crazing 
# 1 = inclusion
# 2 = patches
# 3 = pitted_surface
# 4 = rolled in scale
# 5 = scratches

In [ ]:
dataset1 = pd.read_csv('GLCM_train.csv')
print(dataset1)

      Unnamed: 0    Energy      Corr   Diss_sim   Homogen    Contrast  \
0              0  0.014224  0.725731  15.456080  0.063373  383.715930   
1              0  0.015558  0.778272  12.804573  0.076365  263.964171   
2              0  0.015120  0.746263  13.894296  0.069790  310.096910   
3              0  0.016114  0.719193  13.510452  0.071717  292.011709   
4              0  0.013543  0.787991  14.764347  0.066498  351.571382   
...          ...       ...       ...        ...       ...         ...   
1435           0  0.033905  0.971425   3.316633  0.292426   22.962261   
1436           0  0.058558  0.959366   2.681734  0.485881   48.285804   
1437           0  0.047101  0.983943   2.665603  0.434930   30.869422   
1438           0  0.052825  0.987204   3.837789  0.358781   61.731910   
1439           0  0.052105  0.966701   3.046206  0.392387   38.874296   

       Energy2     Corr2  Diss_sim2  Homogen2  ...   Energy4  Corr4  \
0     0.012683  0.395795  22.695406  0.044695  ...  

In [ ]:
x = dataset1.iloc[:,1:].values
print(len(x[0]))

25


In [ ]:
print(x)

[[1.42235469e-02 7.25731266e-01 1.54560804e+01 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [1.55583846e-02 7.78271956e-01 1.28045729e+01 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [1.51195333e-02 7.46262736e-01 1.38942965e+01 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 ...
 [4.71007360e-02 9.83943252e-01 2.66560302e+00 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [5.28245045e-02 9.87203605e-01 3.83778894e+00 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [5.21048101e-02 9.66701159e-01 3.04620603e+00 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]]


In [ ]:
print(x[0])

[1.42235469e-02 7.25731266e-01 1.54560804e+01 6.33728906e-02
 3.83715930e+02 1.26830436e-02 3.95794743e-01 2.26954061e+01
 4.46945403e-02 8.42411802e+02 1.24517214e-02 2.71204228e-01
 2.48634103e+01 3.97342203e-02 1.01318356e+03 1.05232297e-01
 1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
 1.05232297e-01 1.00000000e+00 0.00000000e+00 1.00000000e+00
 0.00000000e+00]


In [ ]:
print(len(x))

1440


In [ ]:
y = list()

In [ ]:
for i in range(0,6) :
    for j in range(0,240):
        y.append(i)


In [ ]:
print(y)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [ ]:
X_train = x
y_train = y

In [ ]:
dataset1 = pd.read_csv('GLCM_test.csv')
print(dataset1)

     Unnamed: 0    Energy      Corr   Diss_sim   Homogen    Contrast  \
0             0  0.014085  0.748947  15.308317  0.063230  375.439874   
1             0  0.013354  0.812510  14.557965  0.068531  341.479372   
2             0  0.013476  0.759687  15.553065  0.063098  390.181206   
3             0  0.013039  0.771689  15.981709  0.062617  409.665628   
4             0  0.013783  0.757698  15.442638  0.064622  387.517764   
..          ...       ...       ...        ...       ...         ...   
355           0  0.062155  0.995837   1.575452  0.488198    5.920075   
356           0  0.067211  0.985235   1.432513  0.498722    4.875427   
357           0  0.055791  0.988033   2.337362  0.355444   10.801583   
358           0  0.046354  0.989063   2.493492  0.373817   19.243593   
359           0  0.055859  0.979090   2.404749  0.356955   14.151985   

      Energy2     Corr2  Diss_sim2  Homogen2  ...   Energy4  Corr4  Diss_sim4  \
0    0.012467  0.446429  22.532995  0.044155  ...  0.1

In [ ]:
x = dataset1.iloc[:,1:].values
print(len(x[0]))

25


In [ ]:
print(x)
print(x[0])

[[1.40851053e-02 7.48946716e-01 1.53083166e+01 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [1.33542182e-02 8.12510406e-01 1.45579648e+01 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [1.34756312e-02 7.59686590e-01 1.55530653e+01 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 ...
 [5.57906864e-02 9.88033099e-01 2.33736181e+00 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [4.63544075e-02 9.89062761e-01 2.49349246e+00 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [5.58592725e-02 9.79089631e-01 2.40474874e+00 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]]
[1.40851053e-02 7.48946716e-01 1.53083166e+01 6.32298821e-02
 3.75439874e+02 1.24673812e-02 4.46428662e-01 2.25329949e+01
 4.41550228e-02 8.24729797e+02 1.22837374e-02 3.11786677e-01
 2.48204615e+01 4.11062064e-02 1.01926036e+03 1.03558027e-01
 1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
 1.03558027e-01 1.00000000e+00 0.00000000e+00 1.00000000e+00
 0.00000000e+00]


In [ ]:
print(len(x))

360


In [ ]:
y = list()

In [ ]:
for i in range(0,6) :
    for j in range(0,60):
        y.append(i)


In [ ]:
X_test = x
y_test = y

In [ ]:
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

1440
360
1440
360


In [ ]:
X_train=np.array(X_train)
y_train=np.array(y_train)
X_test=np.array(X_test)
y_test=np.array(y_test)

In [ ]:
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (1440, 25) (1440,)
Test set: (360, 25) (360,)


In [ ]:
nsamples, nx = X_train.shape
X_train = X_train.reshape((nsamples,nx))

In [ ]:
print(X_train.shape)

(1440, 25)


In [ ]:
nsamples, nx = X_test.shape
X_test = X_test.reshape((nsamples,nx))

In [ ]:
print(X_test.shape)

(360, 25)


In [ ]:
train_begin = time.time()
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train) 
train_end = time.time()
train_time = train_end - train_begin



In [ ]:
test_begin = time.time()
yhat = clf.predict(X_test)
test_end = time.time()
test_time = test_end - test_begin
print(yhat)

print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))
print(train_time)
print(test_time)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 3 3 1 1 1 1 1 1 1 1 1 1
 3 1 1 1 1 1 1 1 5 1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 3 3 1 1 1 1 1 1 1 1 3 1 1
 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3
 3 3 3 1 5 3 3 3 3 3 3 3 3 3 1 3 3 3 3 3 1 3 1 3 3 3 3 5 3 3 3 3 3 3 3 3 0
 3 5 3 3 3 3 3 3 3 3 1 3 3 5 3 3 1 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 5 1 1 1 1 5 5 5 5 5 1 1 1 5 5 5 1 5 5 1 5 5 5 1 1 5 1 5 1 5 1 5 5
 5 1 5 5 1 1 5 5 5 1 1 1 5 1 1 1 1 4 1 1 1 5 1 1 1 5 5]
0.8583333333333333
[[60  0  0  0  0  0]
 [ 0 52  0  6  0  2]
 [ 1  0 59  0  0  0]
 [ 1  6  0 49  0  4]
 [ 0  0  0  0 60  0]
 [ 0 30  0  0  1 29]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.98        60
           1  

In [ ]:
print(train_time)
print(test_time/len(X_test))

2.5232646465301514
1.868936750623915e-05


In [ ]:
clf = svm.SVC(kernel='rbf', gamma="scale")
clf.fit(X_train, y_train) 
yhat = clf.predict(X_test)
print(yhat)

print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 3 1 1 1 1 1 1 1 1 1 1 1
 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 2 0 2 0 2 2 2 2 2 4 2 0 2 0 2 2 4 2 2 4 0 2 2 4 2 4 2 2
 2 2 2 0 0 2 2 2 0 2 0 2 0 0 0 2 2 2 2 0 2 2 0 4 2 2 2 2 4 0 4 0 0 3 1 5 4
 4 5 3 3 0 3 1 0 3 3 3 3 5 0 1 0 5 5 4 0 1 3 1 0 0 1 3 0 3 0 4 0 0 3 5 3 0
 4 0 3 3 3 3 3 3 5 3 1 3 3 3 1 3 1 3 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 3 3 4
 4 4 4 4 3 4 4 4 4 4 4 4 3 1 4 4 4 4 4 4 3 3 4 3 4 4 3 3 3 4 4 3 3 4 4 4 4
 4 4 4 4 5 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 3 1 1 1 1 1 1 1 1 1 1 1 5 1 1 1
 1 1 1 1 1 1 3 1 1 1 1 1 3 1 1 1 1 5 1 1 1 1 1 1 1 3 1]
0.6333333333333333
[[60  0  0  0  0  0]
 [ 0 58  0  2  0  0]
 [16  0 36  0  8  0]
 [14  9  0 25  5  7]
 [ 0  1  0 13 46  0]
 [ 0 52  0  5  0  3]]
              precision    recall  f1-score   support

           0       0.67      1.00      0.80        60
           1  

In [ ]:
clf = svm.SVC(kernel='rbf', gamma="auto")
clf.fit(X_train, y_train) 
yhat = clf.predict(X_test)
print(yhat)

print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

[2 0 0 2 2 0 2 2 2 0 2 2 2 0 0 0 2 2 0 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 0 2 2 2 2 2 2 0 2 2 2 2 0 2 2 2 2 2 2 0 0 2 1 1 3 3 5 1 1 1 1 1 1 1 1 1
 5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 1 1 1 1 1 1 3 1 3 3 1
 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 3
 3 2 3 5 2 2 3 2 3 3 2 3 2 2 5 2 2 2 3 2 1 3 1 2 2 3 3 2 3 2 2 2 2 2 2 2 2
 2 2 3 2 3 2 2 2 2 3 1 3 2 2 3 3 1 2 4 2 4 4 4 2 4 4 2 2 2 2 4 4 4 4 4 4 4
 4 4 4 2 4 2 4 4 4 2 2 2 4 5 4 2 2 4 4 2 4 4 2 5 4 2 4 4 4 4 4 4 4 4 4 4 4
 4 2 2 4 2 3 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 2 5 1 1 1 5 1 1 1 1 1 1 2 1 1 1
 1 1 1 1 1 1 5 1 1 1 1 1 5 1 1 1 1 2 5 1 5 1 1 1 1 2 1]
0.5194444444444445
[[14  0 46  0  0  0]
 [ 0 51  0  7  0  2]
 [ 2  0 58  0  0  0]
 [ 0  5 35 18  0  2]
 [ 0  0 18  0 40  2]
 [ 0 46  7  1  0  6]]
              precision    recall  f1-score   support

           0       0.88      0.23      0.37        60
           1  

In [ ]:
poly_svc = svm.SVC(kernel='poly', degree=5).fit(X_train, y_train)
yhat = poly_svc.predict(X_test)
print(yhat)
print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

[0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 2 0 2 0 2 2 2 2 2 1 2 0 2 0 2 2 1 2 2 1 0 2 2 1 2 1 2 2
 2 2 2 0 0 2 2 2 0 2 3 2 2 0 0 2 2 2 2 2 2 2 2 1 2 2 2 2 1 2 1 2 0 1 1 1 1
 1 5 1 1 0 1 1 3 1 1 1 3 1 0 1 0 3 5 1 0 1 1 1 0 3 1 1 3 1 3 1 3 0 4 3 1 0
 1 0 1 1 1 1 1 1 3 1 1 1 1 3 1 1 1 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 1 1 1 1 1 1 1 1 1]
0.46944444444444444
[[58  0  0  1  1  0]
 [ 0 60  0  0  0  0]
 [10  8 41  1  0  0]
 [ 9 37  0 10  2  2]
 [ 0 60  0  0  0  0]
 [ 0 59  0  0  1  0]]
              precision    recall  f1-score   support

           0       0.75      0.97      0.85        60
           1 

In [ ]:
for i in range(1,15) :
    poly_svc = svm.SVC(kernel='poly', degree=i).fit(X_train, y_train)
    yhat = poly_svc.predict(X_test)
    print(yhat)
    print('Degree = ',i, metrics.accuracy_score(y_test, yhat))
    # print(confusion_matrix(y_test, yhat))
    # print(classification_report(y_test, yhat))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 2 0 2 0 2 0 2 2 2 4 2 0 2 0 2 2 4 2 2 4 0 2 2 4 2 4 2 2
 2 2 2 0 0 2 2 2 0 2 0 2 0 0 0 2 2 2 2 0 2 2 0 4 2 2 2 2 4 2 4 2 0 4 1 3 4
 4 5 1 4 0 4 1 3 4 4 4 3 5 0 1 0 5 5 4 0 1 4 1 0 3 1 4 3 4 3 4 3 0 4 5 4 0
 4 0 4 3 4 4 4 3 0 1 1 4 3 3 1 4 1 3 4 4 1 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 1 4 4 4 4 4 4 4 1 4 1 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 4 1 1 4 1 1 1 1 1 1 1 1 1 1 1 4 1 1 1
 1 1 1 1 1 1 4 1 1 1 1 1 4 1 1 1 1 5 1 1 1 1 1 1 1 4 1]
Degree =  1 0.6222222222222222
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 

In [ ]:
poly_svc = svm.SVC(kernel='poly', degree=1).fit(X_train, y_train)
yhat = poly_svc.predict(X_test)
print(yhat)
print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 2 0 2 0 2 0 2 2 2 4 2 0 2 0 2 2 4 2 2 4 0 2 2 4 2 4 2 2
 2 2 2 0 0 2 2 2 0 2 0 2 0 0 0 2 2 2 2 0 2 2 0 4 2 2 2 2 4 2 4 2 0 4 1 3 4
 4 5 1 4 0 4 1 3 4 4 4 3 5 0 1 0 5 5 4 0 1 4 1 0 3 1 4 3 4 3 4 3 0 4 5 4 0
 4 0 4 3 4 4 4 3 0 1 1 4 3 3 1 4 1 3 4 4 1 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 1 4 4 4 4 4 4 4 1 4 1 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 4 1 1 4 1 1 1 1 1 1 1 1 1 1 1 4 1 1 1
 1 1 1 1 1 1 4 1 1 1 1 1 4 1 1 1 1 5 1 1 1 1 1 1 1 4 1]
0.6222222222222222
[[59  0  1  0  0  0]
 [ 0 59  0  0  1  0]
 [15  0 37  0  8  0]
 [10 11  0 12 22  5]
 [ 0  4  0  0 56  0]
 [ 0 52  0  0  7  1]]
              precision    recall  f1-score   support

           0       0.70      0.98      0.82        60
           1  