SVM
Feature Extraction Method: GLCM
Features Taken with distance = 5, angle = 0

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
cd /content/drive/"MyDrive/Machine Learning/GLCM"

/content/drive/MyDrive/Machine Learning/GLCM


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import glob
import cv2
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix
import itertools
from skimage.filters import sobel
from skimage.feature import greycomatrix, greycoprops
import time

In [ ]:
X_train = list()
X_test = list()
y_train = list()
y_test = list()

# for k fold cross validation
x_new = list()
y_new = list()

In [ ]:
# 0 = crazing 
# 1 = inclusion
# 2 = patches
# 3 = pitted_surface
# 4 = rolled in scale
# 5 = scratches

In [ ]:
dataset1 = pd.read_csv('GLCM_train.csv')
print(dataset1)

      Unnamed: 0    Energy      Corr   Diss_sim   Homogen    Contrast  \
0              0  0.014224  0.725731  15.456080  0.063373  383.715930   
1              0  0.015558  0.778272  12.804573  0.076365  263.964171   
2              0  0.015120  0.746263  13.894296  0.069790  310.096910   
3              0  0.016114  0.719193  13.510452  0.071717  292.011709   
4              0  0.013543  0.787991  14.764347  0.066498  351.571382   
...          ...       ...       ...        ...       ...         ...   
1435           0  0.033905  0.971425   3.316633  0.292426   22.962261   
1436           0  0.058558  0.959366   2.681734  0.485881   48.285804   
1437           0  0.047101  0.983943   2.665603  0.434930   30.869422   
1438           0  0.052825  0.987204   3.837789  0.358781   61.731910   
1439           0  0.052105  0.966701   3.046206  0.392387   38.874296   

       Energy2     Corr2  Diss_sim2  Homogen2  ...   Energy4  Corr4  \
0     0.012683  0.395795  22.695406  0.044695  ...  

In [ ]:
x = dataset1.iloc[:,11:16].values
print(len(x[0]))

5


In [ ]:
print(x)

[[1.24517214e-02 2.71204228e-01 2.48634103e+01 3.97342203e-02
  1.01318356e+03]
 [1.34048379e-02 4.41275423e-01 2.01172051e+01 5.08597913e-02
  6.57472590e+02]
 [1.32462640e-02 3.76921626e-01 2.15380256e+01 4.70296571e-02
  7.47128641e+02]
 ...
 [3.33351676e-02 8.35100932e-01 8.23856410e+00 2.50575371e-01
  3.21118462e+02]
 [3.48665720e-02 8.64707627e-01 1.21986667e+01 1.84690935e-01
  6.62054513e+02]
 [4.12908734e-02 8.18317591e-01 6.79512821e+00 2.48585891e-01
  2.13973590e+02]]


In [ ]:
print(x[0])

[1.24517214e-02 2.71204228e-01 2.48634103e+01 3.97342203e-02
 1.01318356e+03]


In [ ]:
print(len(x))

1440


In [ ]:
y = list()

In [ ]:
for i in range(0,6) :
    for j in range(0,240):
        y.append(i)


In [ ]:
print(y)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [ ]:
X_train = x
y_train = y

In [ ]:
dataset1 = pd.read_csv('GLCM_test.csv')
print(dataset1)

     Unnamed: 0    Energy      Corr   Diss_sim   Homogen    Contrast  \
0             0  0.014085  0.748947  15.308317  0.063230  375.439874   
1             0  0.013354  0.812510  14.557965  0.068531  341.479372   
2             0  0.013476  0.759687  15.553065  0.063098  390.181206   
3             0  0.013039  0.771689  15.981709  0.062617  409.665628   
4             0  0.013783  0.757698  15.442638  0.064622  387.517764   
..          ...       ...       ...        ...       ...         ...   
355           0  0.062155  0.995837   1.575452  0.488198    5.920075   
356           0  0.067211  0.985235   1.432513  0.498722    4.875427   
357           0  0.055791  0.988033   2.337362  0.355444   10.801583   
358           0  0.046354  0.989063   2.493492  0.373817   19.243593   
359           0  0.055859  0.979090   2.404749  0.356955   14.151985   

      Energy2     Corr2  Diss_sim2  Homogen2  ...   Energy4  Corr4  Diss_sim4  \
0    0.012467  0.446429  22.532995  0.044155  ...  0.1

In [ ]:
x = dataset1.iloc[:,11:16].values
print(len(x[0]))

5


In [ ]:
print(x)
print(x[0])

[[1.22837374e-02 3.11786677e-01 2.48204615e+01 4.11062064e-02
  1.01926036e+03]
 [1.15904810e-02 5.32045089e-01 2.26312564e+01 4.52681077e-02
  8.34160744e+02]
 [1.16493814e-02 3.58520753e-01 2.51179487e+01 4.20494281e-02
  1.04075026e+03]
 ...
 [3.99379203e-02 9.27688946e-01 5.25128205e+00 1.95771812e-01
  6.49314872e+01]
 [3.36716754e-02 9.03525199e-01 6.17061538e+00 2.19845428e-01
  1.71253436e+02]
 [4.14036432e-02 8.88943344e-01 5.00961538e+00 2.13126563e-01
  7.41732051e+01]]
[1.22837374e-02 3.11786677e-01 2.48204615e+01 4.11062064e-02
 1.01926036e+03]


In [ ]:
print(len(x))

360


In [ ]:
y = list()

In [ ]:
for i in range(0,6) :
    for j in range(0,60):
        y.append(i)


In [ ]:
X_test = x
y_test = y

In [ ]:
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

1440
360
1440
360


In [ ]:
X_train=np.array(X_train)
y_train=np.array(y_train)
X_test=np.array(X_test)
y_test=np.array(y_test)

In [ ]:
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (1440, 5) (1440,)
Test set: (360, 5) (360,)


In [ ]:
nsamples, nx = X_train.shape
X_train = X_train.reshape((nsamples,nx))

In [ ]:
print(X_train.shape)

(1440, 5)


In [ ]:
nsamples, nx = X_test.shape
X_test = X_test.reshape((nsamples,nx))

In [ ]:
print(X_test.shape)

(360, 5)


In [ ]:
train_begin = time.time()
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train) 
train_end = time.time()
train_time = train_end - train_begin



In [ ]:
test_begin = time.time()
yhat = clf.predict(X_test)
test_end = time.time()
test_time = test_end - test_begin
print(yhat)

print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))
print(train_time)
print(test_time)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 2
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 3 3 1 1 1 3 1 1 3 1 1 1
 3 1 1 1 1 1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 3 3 1 1 1 1 1 1 1 1 3 1 1
 1 1 1 1 1 1 3 3 1 2 2 2 2 2 2 2 2 2 4 2 2 2 2 2 2 4 2 2 4 2 2 2 4 2 3 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 4 2 4 2 0 3 3 3 3
 3 0 3 3 0 4 3 0 4 4 4 0 3 0 3 0 2 0 3 0 1 4 1 0 2 3 3 3 3 0 3 0 0 3 0 3 0
 3 0 3 3 4 4 3 4 0 3 1 3 4 3 3 3 1 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 5 1 1 1 1 5 5 5 5 5 1 1 1 1 5 3 1 5 5 1 3 1 5 1 1 1 1 5 1 5 1 5 1
 5 1 1 3 1 1 5 1 1 1 1 1 5 1 1 1 1 5 1 1 3 1 1 1 1 5 5]
0.7333333333333333
[[57  0  3  0  0  0]
 [ 0 48  0 11  0  1]
 [ 0  0 52  2  6  0]
 [17  4  2 28  9  0]
 [ 0  0  0  0 60  0]
 [ 0 37  0  4  0 19]]
              precision    recall  f1-score   support

           0       0.77      0.95      0.85        60
           1  

In [ ]:
print(train_time)
print(test_time/len(X_test))

6.329472303390503
4.1066937976413306e-05


In [ ]:
clf = svm.SVC(kernel='rbf', gamma="scale")
clf.fit(X_train, y_train) 
yhat = clf.predict(X_test)
print(yhat)

print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

[2 0 2 2 2 0 2 2 2 2 2 2 4 2 2 0 2 2 0 0 2 2 2 0 2 2 0 2 0 0 2 2 2 2 2 2 2
 2 2 0 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 0 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 0 0 0 2 0 2 2 2 4 2 0 2 0 2 2 4 2 0 4 0 2 0 4 2 4 2 2
 2 2 0 0 0 2 2 0 0 2 0 0 0 0 0 2 2 2 0 2 0 2 0 4 0 2 2 2 4 0 4 0 0 4 1 4 4
 4 0 4 4 0 4 1 0 4 4 4 0 4 0 3 0 0 2 4 0 1 4 1 0 0 1 4 0 4 0 4 0 0 4 0 4 0
 4 0 3 4 4 4 4 4 0 1 1 4 4 0 1 3 1 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 3 3 4
 4 4 4 4 3 4 4 4 4 4 4 4 4 1 4 4 4 4 4 4 3 3 4 1 4 4 4 3 3 4 4 4 4 4 4 4 4
 4 4 4 4 4 1 1 1 1 3 1 1 1 1 1 1 1 1 4 1 1 4 1 1 3 1 1 1 1 1 1 1 1 4 1 1 1
 1 1 1 1 1 1 4 1 1 1 1 1 4 1 1 1 1 0 1 1 1 1 1 1 1 4 1]
0.41944444444444445
[[13  0 46  0  1  0]
 [ 0 59  0  0  1  0]
 [26  0 26  0  8  0]
 [20  9  1  3 27  0]
 [ 0  2  0  8 50  0]
 [ 1 50  0  2  7  0]]
              precision    recall  f1-score   support

           0       0.22      0.22      0.22        60
           1 

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
clf = svm.SVC(kernel='rbf', gamma="auto")
clf.fit(X_train, y_train) 
yhat = clf.predict(X_test)
print(yhat)

print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

[2 0 0 2 2 0 0 0 2 2 0 2 2 0 0 2 0 2 0 0 0 2 2 2 2 2 0 2 2 0 0 2 2 2 0 0 0
 0 0 2 0 0 2 0 2 0 2 2 0 0 0 0 2 2 0 2 0 0 2 0 1 1 3 3 1 1 1 1 1 1 1 1 1 1
 3 5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 3 1 1 1 1 1 1 1 1 3 1 1
 1 1 1 1 1 1 1 1 1 2 2 0 0 2 2 2 0 2 4 2 3 0 0 2 2 4 2 0 4 0 2 2 4 2 2 2 2
 2 2 0 2 2 2 2 2 2 2 0 0 0 0 2 2 2 2 0 2 2 2 2 4 0 2 0 0 4 0 4 2 0 3 1 3 3
 3 0 3 3 0 4 1 2 3 3 3 3 3 2 3 2 0 3 3 2 1 3 1 0 2 1 4 0 4 0 4 0 3 4 2 3 2
 4 2 4 4 2 4 4 4 2 3 1 4 4 2 3 4 1 2 3 4 3 3 3 4 3 4 4 4 4 4 4 3 3 4 4 3 4
 3 3 3 4 4 4 4 4 4 4 4 4 3 3 4 4 4 3 3 4 4 3 4 3 4 4 3 4 4 3 4 3 3 4 4 3 4
 4 4 4 3 5 1 1 1 1 5 1 5 5 1 1 1 1 1 5 3 1 5 5 1 3 1 5 1 1 1 1 5 5 5 1 1 1
 5 1 1 1 1 1 5 1 1 1 1 1 2 1 1 1 1 2 1 1 5 1 1 1 1 5 5]
0.5333333333333333
[[32  0 28  0  0  0]
 [ 0 53  0  6  0  1]
 [17  0 35  1  7  0]
 [ 8  7 12 19 14  0]
 [ 0  0  0 23 37  0]
 [ 0 40  2  2  0 16]]
              precision    recall  f1-score   support

           0       0.56      0.53      0.55        60
           1  

In [ ]:
poly_svc = svm.SVC(kernel='poly', degree=5).fit(X_train, y_train)
yhat = poly_svc.predict(X_test)
print(yhat)
print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

[0 0 0 0 0 3 0 0 2 0 0 0 4 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 3 2 2 3 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 2 0 0 3 2 0 0 2 2 1 2 3 2 3 2 2 1 2 0 1 3 2 0 1 2 1 2 2
 0 0 0 0 3 2 0 0 3 2 3 0 0 3 3 2 2 2 0 0 0 2 3 1 0 2 0 0 1 0 1 3 3 1 1 1 1
 1 0 1 1 3 1 1 3 1 1 1 3 4 3 1 3 3 0 1 3 1 1 1 3 3 1 1 3 1 3 1 3 3 1 3 1 3
 1 3 1 1 1 1 1 1 0 1 1 1 1 3 1 1 1 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 1 1]
0.41388888888888886
[[51  0  5  3  1  0]
 [ 0 60  0  0  0  0]
 [21  8 20 11  0  0]
 [ 3 37  0 18  2  0]
 [ 0 60  0  0  0  0]
 [ 0 59  0  1  0  0]]
              precision    recall  f1-score   support

           0       0.68      0.85      0.76        60
           1 

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
for i in range(1,15) :
    poly_svc = svm.SVC(kernel='poly', degree=i).fit(X_train, y_train)
    yhat = poly_svc.predict(X_test)
    print(yhat)
    print('Degree = ',i, metrics.accuracy_score(y_test, yhat))
    # print(confusion_matrix(y_test, yhat))
    # print(classification_report(y_test, yhat))

[2 0 2 2 2 0 2 2 2 2 2 2 4 2 2 0 2 2 0 0 2 2 2 0 2 2 2 2 0 0 2 2 2 2 2 2 2
 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 0 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 2 0 2 0 2 0 2 2 2 4 2 5 2 5 2 2 4 2 2 4 0 2 2 4 2 4 2 2
 2 2 0 0 0 2 2 0 0 2 3 0 0 0 5 2 2 2 2 2 0 2 0 4 2 2 2 2 4 0 4 0 0 4 1 4 4
 4 2 4 4 0 4 1 5 4 4 4 3 4 0 1 0 0 2 4 0 1 4 1 0 0 1 4 0 4 5 4 5 0 4 0 4 0
 4 0 1 4 4 4 4 4 0 1 1 4 4 5 1 1 1 4 4 4 1 4 4 4 4 4 4 4 4 4 4 4 4 4 1 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 1 4 4 4 4 4 4 1 1 4 1 4 4 4 1 1 4 4 4 4 4 4 4 4
 4 4 4 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 4 1 1 4 1 1 1 1 1 1 1 1 1 1 1 4 1 1 1
 1 1 1 1 1 1 4 1 1 1 1 1 4 1 1 1 1 5 1 1 1 1 1 1 1 4 1]
Degree =  1 0.4305555555555556
[2 0 2 2 2 0 2 2 2 0 2 2 4 2 2 0 2 2 0 0 2 2 2 0 2 2 0 2 0 0 2 2 2 2 2 2 0
 2 2 0 2 2 2 0 2 0 2 2 2 2 2 2 2 2 2 3 2 2 0 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 

In [ ]:
poly_svc = svm.SVC(kernel='poly', degree=9).fit(X_train, y_train)
yhat = poly_svc.predict(X_test)
print(yhat)
print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

[0 0 0 0 0 3 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 3 0 0 0 0 0 0 2
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 3 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 2 0 2 3 2 2 2 2 2 1 2 3 2 4 2 2 1 2 2 1 3 2 2 1 2 1 2 2
 2 2 0 0 3 2 2 3 3 2 4 0 3 3 3 2 2 2 2 2 2 2 3 1 2 2 2 2 1 3 1 3 3 1 1 1 1
 1 0 1 1 3 1 1 3 1 1 1 4 1 3 1 3 3 2 1 3 1 1 1 3 3 1 1 3 1 3 1 3 3 1 3 1 3
 1 3 1 1 1 1 1 1 0 1 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 1 1 1 1 1 1 1 1 1]
0.45555555555555555
[[53  1  2  3  1  0]
 [ 0 60  0  0  0  0]
 [ 4  8 34 12  2  0]
 [ 2 39  1 17  1  0]
 [ 0 60  0  0  0  0]
 [ 0 59  0  0  1  0]]
              precision    recall  f1-score   support

           0       0.90      0.88      0.89        60
           1 

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
