TWIN SVM
Features: Energy, Dots, Lines, Contours, Edges, Corners

In [ ]:
from TVSVM import TwinSVMClassifier

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
cd /content/drive/"MyDrive/Machine Learning/Excel"

/content/drive/MyDrive/Machine Learning/Excel


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
import glob
import cv2
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix
import itertools
import random
import time

In [ ]:
X_train = list()
X_test = list()
y_train = list()
y_test = list()

# for k fold cross validation
x_new = list()
y_new = list()

In [ ]:
# 0 = crazing 
# 1 = inclusion
# 2 = patches
# 3 = pitted_surface
# 4 = rolled in scale
# 5 = scratches

In [ ]:
dataset1 = pd.read_csv('neudefect1.csv')
print(dataset1)

x = dataset1.iloc[:,:-1].values
print(len(x[0]))

y = list()


print(x[0])
print(x[499])

for i in x:
    x_new.append(i)


random.shuffle(x)
print(x[0])
print(x[499])


for i in range(0,600):
    y.append(0)
    y_new.append(0)


X_train_new, X_test_new, y_train_new, y_test_new = train_test_split( x, y, test_size=0.2, random_state=4)
print(X_test_new)

for i in X_train_new :
    X_train.append(i)

for i in X_test_new :
    X_test.append(i)

for i in y_train_new :
    y_train.append(i)

for i in y_test_new :
    y_test.append(i)

print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

         energy  dots  lines  contours  edges  corner   
0     96.995963   184    186         6   8574      13   
1     96.995963   184    186         3   8637       7   
2    107.102900   216    106         3   9968      15   
3    107.102900   216    106         3   9961      19   
4    123.340781   350     19         9  11597       9   
..          ...   ...    ...       ...    ...     ... ..
595  140.306469   280     38        12  11715       2   
596  127.175844   215     66         3  10576       9   
597  127.175844   215     66         2  10571       6   
598   55.432938   177    519         3   3705       9   
599   55.432938   177    519         3   3708       3   

[600 rows x 7 columns]
6
[9.69959625e+01 1.84000000e+02 1.86000000e+02 6.00000000e+00
 8.57400000e+03 1.30000000e+01]
[3.59366625e+01 1.30000000e+02 5.69000000e+02 1.00000000e+00
 1.15800000e+03 6.10000000e+01]
[9.69959625e+01 1.84000000e+02 1.86000000e+02 6.00000000e+00
 8.57400000e+03 1.30000000e+01]
[1.62199525

In [ ]:
dataset1 = pd.read_csv('neudefect2.csv')
print(dataset1)

x = dataset1.iloc[:,:-1].values
print(len(x[0]))

y = list()


print(x[0])
print(x[499])


random.shuffle(x)
print(x[0])
print(x[499])

for i in x:
    x_new.append(i)


for i in range(0,600):
    y.append(1)
    y_new.append(1)


X_train_new, X_test_new, y_train_new, y_test_new = train_test_split( x, y, test_size=0.2, random_state=4)
print(X_test_new)

for i in X_train_new :
    X_train.append(i)

for i in X_test_new :
    X_test.append(i)

for i in y_train_new :
    y_train.append(i)

for i in y_test_new :
    y_test.append(i)

print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

       energy  dots  lines  contours  edges  corner   
0    4.118869    66      9         1     21      98   
1    4.118869    66      9         1     21      84   
2    4.024788    53      8         1     21      87   
3    4.024788    53      8         1     21      85   
4    3.838606    41    295         1      0     110   
..        ...   ...    ...       ...    ...     ... ..
595  3.103481    78     16         1      0     194   
596  2.751100    88    319         1      0     187   
597  2.751100    88    319         1      0     155   
598  2.689631   107    415         1      0     139   
599  2.689631   107    415         2      0     149   

[600 rows x 7 columns]
6
[ 4.11886875 66.          9.          1.         21.         98.        ]
[ 4.3154375 94.        39.         1.         0.        66.       ]
[ 4.11886875 66.          9.          1.         21.         98.        ]
[  2.5119375  80.        342.          1.          0.        113.       ]
[[  2.423525    92.     

In [ ]:
dataset1 = pd.read_csv('neudefect3.csv')
print(dataset1)

x = dataset1.iloc[:,:-1].values
print(len(x[0]))

y = list()


print(x[0])
print(x[499])


random.shuffle(x)
print(x[0])
print(x[499])


for i in x:
    x_new.append(i)

for i in range(0,600):
    y.append(2)
    y_new.append(2)


X_train_new, X_test_new, y_train_new, y_test_new = train_test_split( x, y, test_size=0.2, random_state=4)
print(X_test_new)

for i in X_train_new :
    X_train.append(i)

for i in X_test_new :
    X_test.append(i)

for i in y_train_new :
    y_train.append(i)

for i in y_test_new :
    y_test.append(i)

print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

         energy  dots  lines  contours  edges  corner   
0    144.344288   134    130        38  11030      15   
1    144.344288   134    130        35  11016      13   
2    117.202019   184     99        11   9368      14   
3    117.202019   184     99         5   9333      15   
4     75.079475   101    215        18   5371      20   
..          ...   ...    ...       ...    ...     ... ..
595   15.830294   192     37         3      8     115   
596   62.683950    27    118        27   4415       7   
597   62.683950    27    118        27   4433      13   
598   57.148769    47    223        50   4173      38   
599   57.148769    47    223        53   4150      42   

[600 rows x 7 columns]
6
[  144.3442875   134.          130.           38.        11030.
    15.       ]
[  99.93188125   51.          139.           57.         6801.
   39.        ]
[  144.3442875   134.          130.           38.        11030.
    15.       ]
[ 104.86659375  122.          165.           26.   

In [ ]:
dataset1 = pd.read_csv('neudefect4.csv')
print(dataset1)

x = dataset1.iloc[:,:-1].values
print(len(x[0]))

y = list()


print(x[0])
print(x[499])

for i in x:
    x_new.append(i)

random.shuffle(x)
print(x[0])
print(x[499])


for i in range(0,600):
    y.append(3)
    y_new.append(3)


X_train_new, X_test_new, y_train_new, y_test_new = train_test_split( x, y, test_size=0.2, random_state=4)
print(X_test_new)

for i in X_train_new :
    X_train.append(i)

for i in X_test_new :
    X_test.append(i)

for i in y_train_new :
    y_train.append(i)

for i in y_test_new :
    y_test.append(i)

print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

        energy  dots  lines  contours  edges  corner   
0     4.900825    45    218         1      0     145   
1     4.900825    45    218         1      0      84   
2     4.910156    14    115         1      0      38   
3     4.910156    14    115         1      0      45   
4    15.046094    86      0         1    784      50   
..         ...   ...    ...       ...    ...     ... ..
595   6.341663    49    140         2      0     105   
596  16.225606   110      0         1    596       7   
597  16.225606   110      0         1    596      10   
598  15.959525   118      0         3    308       6   
599  15.959525   118      0         2    307       6   

[600 rows x 7 columns]
6
[  4.900825  45.       218.         1.         0.       145.      ]
[14.232975 87.        0.        1.       66.       12.      ]
[  4.900825  45.       218.         1.         0.       145.      ]
[2.57401313e+01 1.18000000e+02 0.00000000e+00 1.00000000e+00
 1.78100000e+03 5.00000000e+00]
[[6.0488725

In [ ]:
dataset1 = pd.read_csv('neudefect5.csv')
print(dataset1)

x = dataset1.iloc[:,:-1].values
print(len(x[0]))

y = list()


print(x[0])
print(x[499])


random.shuffle(x)
print(x[0])
print(x[499])

for i in x:
    x_new.append(i)

for i in range(0,600):
    y.append(4)
    y_new.append(4)


X_train_new, X_test_new, y_train_new, y_test_new = train_test_split( x, y, test_size=0.2, random_state=4)
print(X_test_new)

for i in X_train_new :
    X_train.append(i)

for i in X_test_new :
    X_test.append(i)

for i in y_train_new :
    y_train.append(i)

for i in y_test_new :
    y_test.append(i)

print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

        energy  dots  lines  contours  edges  corner   
0    27.866075   231      0         1    144     123   
1    27.866075   231      0         1    138     160   
2    24.338119   218     32         1    211     183   
3    24.338119   218     32         1    213      52   
4    18.673944   324     63         9      0       8   
..         ...   ...    ...       ...    ...     ... ..
595  19.063156   247     94         6     40       4   
596  33.260206   156     25         2    586      10   
597  33.260206   156     25         2    576      13   
598  30.911975   216     21         2    476       5   
599  30.911975   216     21         2    463       5   

[600 rows x 7 columns]
6
[ 27.866075 231.         0.         1.       144.       123.      ]
[ 25.7831375 152.         12.          1.        597.          8.       ]
[ 27.866075 231.         0.         1.       144.       123.      ]
[ 25.3854 207.      23.       3.     167.       6.    ]
[[3.13297125e+01 3.38000000e+02 5.60

In [ ]:
dataset1 = pd.read_csv('neudefect6.csv')
print(dataset1)

x = dataset1.iloc[:,:-1].values
print(len(x[0]))

y = list()


print(x[0])
print(x[499])


random.shuffle(x)
print(x[0])
print(x[499])

for i in x:
    x_new.append(i)

for i in range(0,600):
    y.append(5)
    y_new.append(5)


X_train_new, X_test_new, y_train_new, y_test_new = train_test_split( x, y, test_size=0.2, random_state=4)
print(X_test_new)

for i in X_train_new :
    X_train.append(i)

for i in X_test_new :
    X_test.append(i)

for i in y_train_new :
    y_train.append(i)

for i in y_test_new :
    y_test.append(i)

print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

        energy  dots  lines  contours  edges  corner   
0     3.930488   120     17         1    154       3   
1     3.930488   120     17         1    154       3   
2    24.651506    42     32         5    848       9   
3    24.651506    42     32         5    848       9   
4    17.056650    14      7        11    717      16   
..         ...   ...    ...       ...    ...     ... ..
595  10.991888    62      2         2    536       3   
596   5.499306    79    416         2     98      17   
597   5.499306    79    416         2     98      17   
598  13.290188     5    116        10    546       9   
599  13.290188     5    116        10    546       9   

[600 rows x 7 columns]
6
[  3.9304875 120.         17.          1.        154.          3.       ]
[  13.1159875   20.           0.           4.        1246.
    6.       ]
[  3.9304875 120.         17.          1.        154.          3.       ]
[  5.3968125  11.         10.          1.        325.          6.       ]
[[2.32

In [ ]:
print(y_train)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
print(len(x_new))
print(len(y_new))

3600
3600


In [ ]:
X_train=np.array(X_train)
y_train=np.array(y_train)
X_test=np.array(X_test)
y_test=np.array(y_test)

In [ ]:
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (2880, 6) (2880,)
Test set: (720, 6) (720,)


In [ ]:
nsamples, nx = X_train.shape
X_train = X_train.reshape((nsamples,nx))

In [ ]:
print(X_train.shape)

(2880, 6)


In [ ]:
nsamples, nx = X_test.shape
X_test = X_test.reshape((nsamples,nx))

In [ ]:
print(X_test.shape)

(720, 6)


In [ ]:
train_begin = time.time()
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train) 
train_end = time.time()
train_time = train_end - train_begin



In [ ]:
test_begin = time.time()
yhat = clf.predict(X_test)
test_end = time.time()
test_time = test_end - test_begin
print(yhat)

print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))
print(train_time)
print(test_time)

[0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 2 0 0 0 0 0 0 0 2 0 0 0
 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 3 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 3 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3
 1 3 1 1 3 5 3 4 1 3 2 3 5 3 3 3 3 3 1 3 3 3 3 1 3 3 3 3 3 3 3 3 1 3 3 3 3
 3 3 3 3 3 1 1 3 3 3 3 3 3 3 1 3 3 3 3 5 3 3 3 3 1 3 1 3 3 3 3 3 3 3 3 1 3
 3 3 3 1 3 5 3 1 1 3 3 3 3 3 3 3 1 3 3 3 3 3 3 3 3 3 1 1 1 3 5 1 3 3 3 3 4
 4 4 4 4 4 4 4 4 4 4 4 4 

In [ ]:
print(train_time)
print(test_time/len(X_test))

185.59272360801697
2.2055043114556208e-05


In [ ]:
clf = svm.SVC(kernel='rbf', gamma="scale")
clf.fit(X_train, y_train) 
yhat = clf.predict(X_test)
print(yhat)

print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

[0 0 0 0 0 0 0 2 0 0 2 0 0 2 0 2 2 2 0 0 2 0 0 0 0 2 0 0 2 0 0 0 2 0 0 0 2
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 2 2 0
 0 2 0 0 0 4 0 0 2 2 0 2 2 0 0 0 2 0 0 0 2 0 0 0 0 0 0 0 0 2 2 2 0 0 0 4 0
 0 0 0 0 0 2 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 5 2 2 2 5 2 2 2 5 2 2 2 2 2 5 0 2
 2 2 1 2 2 0 2 4 2 5 2 2 5 2 0 0 2 2 2 2 2 2 0 2 2 2 2 2 2 5 2 2 2 0 5 0 2
 2 2 2 2 2 0 2 2 2 2 2 2 4 2 2 2 2 0 2 2 2 5 2 2 0 2 2 2 2 2 2 2 0 5 2 2 2
 5 2 5 2 0 5 2 1 2 1 2 2 2 2 2 2 0 2 0 2 2 2 2 2 2 2 2 1 3 1 1 1 1 5 3 5 1
 1 5 1 5 1 1 1 1 5 5 5 3 4 5 4 5 1 3 1 1 1 1 5 1 2 1 2 3 1 3 5 5 1 3 2 3 3
 3 3 2 3 1 1 1 1 5 1 2 5 5 1 5 3 5 1 4 4 3 3 5 2 5 5 1 1 5 1 3 1 5 1 1 5 2
 4 1 1 1 3 3 5 3 2 5 1 5 3 1 5 1 1 5 5 1 1 5 1 4 1 1 5 1 3 1 1 1 1 1 1 1 4
 4 4 4 4 4 4 4 1 1 4 1 4 

In [ ]:
clf = svm.SVC(kernel='rbf', gamma="auto")
clf.fit(X_train, y_train) 
yhat = clf.predict(X_test)
print(yhat)

print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

[0 0 0 0 0 0 2 0 2 0 2 0 0 0 0 0 0 2 0 0 0 0 2 0 0 0 0 0 2 0 0 2 2 0 2 2 0
 0 0 2 0 0 0 2 0 2 0 2 0 2 2 0 2 0 0 2 0 2 0 2 0 0 2 0 0 0 0 0 0 2 0 2 2 0
 0 2 0 2 0 2 2 2 0 0 0 0 0 0 2 2 2 0 0 2 2 0 2 0 2 2 0 0 2 0 0 0 0 0 0 0 0
 0 2 0 0 0 0 0 2 0 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 2 1 2 1 1 1 1 1 1 1 1
 2 1 2 1 1 1 2 2 1 1 1 2 1 1 1 2 2 1 1 1 1 1 2 1 1 1 1 1 1 2 1 1 1 2 1 1 1
 1 1 1 1 2 1 1 1 1 2 1 2 1 1 1 1 1 1 2 2 1 1 1 1 2 1 2 1 1 1 1 1 1 2 1 1 2
 1 1 1 1 1 2 1 1 1 1 1 1 1 2 2 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 3 2 3 3 3 2 3 3
 2 3 3 3 3 3 2 2 3 3 3 3 2 3 3 3 3 3 3 3 3 2 3 3 2 2 3 3 2 2 3 2 3 2 2 3 2
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 2 3 3 3 3 3 3 2 3 3 3 3 2 3 3 3 3 3 3
 2 3 3 3 2 2 2 2 2 2 3 3 3 3 2 3 3 2 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 2 2
 2 2 4 4 4 4 2 2 4 2 4 4 

In [ ]:
poly_svc = svm.SVC(kernel='poly', degree=5).fit(X_train, y_train)
yhat = poly_svc.predict(X_test)
print(yhat)
print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

[0 3 0 0 5 0 0 0 0 0 0 5 0 0 5 0 0 0 2 0 0 0 0 5 0 2 0 3 0 0 0 0 2 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 2 5 0 0 0 0 2 5 0 0 0 0 0 0 0
 0 0 0 0 5 1 0 0 2 0 0 0 2 0 0 0 0 3 5 0 0 0 0 0 0 0 0 0 0 2 0 0 5 0 0 1 0
 3 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 2 2 2 1 2 2 2 1 2 0 2 0 2 1 2 2
 2 2 1 2 2 2 5 1 2 1 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 1 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 3 2 2 2 2 2 1 2 3 3 2 2 2 2 2 2 2 5 1 2 2 2
 1 2 1 2 3 1 3 1 3 1 2 2 5 2 2 0 3 2 2 2 2 2 0 2 2 2 2 1 4 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 4 1 1 1 1 1 1 3 1 3 4 1 4 1 1 1 1 3 3 1
 1 4 3 1 1 1 1 1 1 1 3 1 1 1 1 4 1 1 1 1 1 3 1 3 1 1 1 1 1 1 3 1 1 1 1 1 3
 1 1 1 1 4 3 1 3 3 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [ ]:
for i in range(1,8) :
    poly_svc = svm.SVC(kernel='poly', degree=i).fit(X_train, y_train)
    yhat = poly_svc.predict(X_test)
    print(yhat)
    print('Degree = ',i, metrics.accuracy_score(y_test, yhat))
    # print(confusion_matrix(y_test, yhat))
    # print(classification_report(y_test, yhat))

[0 2 0 0 2 0 0 0 0 0 2 2 0 0 0 2 2 0 2 0 0 0 0 2 0 2 0 2 0 0 0 0 2 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 2 2 0 0 2 0 2 2 0 0 0 0 2 0 0
 0 2 0 0 2 4 0 0 2 0 0 0 2 0 0 0 2 2 2 0 0 0 0 0 0 0 0 0 0 2 0 0 2 0 0 4 0
 2 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 5 2 2 2 5 2 2 2 5 2 2 2 0 2 5 0 2
 2 2 1 2 2 0 3 4 2 1 2 2 5 2 0 0 2 2 2 2 2 2 0 2 2 2 2 2 2 5 2 2 2 0 5 0 2
 2 2 2 2 2 0 2 2 2 2 2 2 4 2 2 2 2 0 0 2 2 1 2 2 2 2 2 2 0 2 2 2 0 5 2 2 2
 1 2 5 2 2 5 2 1 2 1 2 2 3 2 2 2 2 2 0 2 2 2 2 2 2 2 2 1 3 1 1 1 1 5 5 3 1
 1 5 1 5 1 1 1 1 5 5 5 2 5 5 4 5 1 3 1 1 1 1 5 1 2 1 2 3 1 3 5 5 1 3 2 3 5
 5 3 2 5 1 1 1 1 5 1 2 5 5 1 5 3 5 1 5 4 5 3 3 2 5 5 1 1 5 1 3 1 3 1 1 5 2
 4 1 1 1 3 3 5 3 2 3 1 5 3 1 5 1 1 5 5 1 1 5 1 4 1 1 5 1 2 1 1 1 1 1 1 1 4
 1 4 4 4 4 1 4 1 1 4 1 3 

In [ ]:
poly_svc = svm.SVC(kernel='poly', degree=1).fit(X_train, y_train)
yhat = poly_svc.predict(X_test)
print(yhat)
print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

[0 2 0 0 2 0 0 0 0 0 2 2 0 0 0 2 2 0 2 0 0 0 0 2 0 2 0 2 0 0 0 0 2 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 2 2 0 0 2 0 2 2 0 0 0 0 2 0 0
 0 2 0 0 2 4 0 0 2 0 0 0 2 0 0 0 2 2 2 0 0 0 0 0 0 0 0 0 0 2 0 0 2 0 0 4 0
 2 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 5 2 2 2 5 2 2 2 5 2 2 2 0 2 5 0 2
 2 2 1 2 2 0 3 4 2 1 2 2 5 2 0 0 2 2 2 2 2 2 0 2 2 2 2 2 2 5 2 2 2 0 5 0 2
 2 2 2 2 2 0 2 2 2 2 2 2 4 2 2 2 2 0 0 2 2 1 2 2 2 2 2 2 0 2 2 2 0 5 2 2 2
 1 2 5 2 2 5 2 1 2 1 2 2 3 2 2 2 2 2 0 2 2 2 2 2 2 2 2 1 3 1 1 1 1 5 5 3 1
 1 5 1 5 1 1 1 1 5 5 5 2 5 5 4 5 1 3 1 1 1 1 5 1 2 1 2 3 1 3 5 5 1 3 2 3 5
 5 3 2 5 1 1 1 1 5 1 2 5 5 1 5 3 5 1 5 4 5 3 3 2 5 5 1 1 5 1 3 1 3 1 1 5 2
 4 1 1 1 3 3 5 3 2 3 1 5 3 1 5 1 1 5 5 1 1 5 1 4 1 1 5 1 2 1 1 1 1 1 1 1 4
 1 4 4 4 4 1 4 1 1 4 1 3 

In [ ]:
# k Fold cross validation
# k fold cross validation
from sklearn.model_selection import KFold,RepeatedKFold 
kf = RepeatedKFold(n_splits=5, n_repeats=10, random_state=2652124) 

for train_index, test_index in kf.split(x_new):
      #print("Train:", train_index, "Validation:",test_index)
      #X_train_new, X_test_new = x_new[train_index], x_new[test_index] 
      X_train_new, X_test_new = np.array(x_new)[train_index.astype(int)], np.array(x_new)[test_index.astype(int)]
      #y_train_new, y_test_new = y_new[train_index], y_new[test_index]
      y_train_new, y_test_new = np.array(y_new)[train_index.astype(int)], np.array(y_new)[test_index.astype(int)]
      
      
      clf = svm.SVC(kernel='linear')
      clf.fit(X_train, y_train) 
      yhat = clf.predict(X_test)
      print(metrics.accuracy_score(y_test, yhat))
      print(confusion_matrix(y_test, yhat))
      print(classification_report(y_test, yhat))

0.9291666666666667
[[119   0   1   0   0   0]
 [  0 114   0   5   0   1]
 [  8   0 112   0   0   0]
 [  0  18   0 101   0   1]
 [  0   0   2   0 118   0]
 [  0   6   0   9   0 105]]
              precision    recall  f1-score   support

           0       0.94      0.99      0.96       120
           1       0.83      0.95      0.88       120
           2       0.97      0.93      0.95       120
           3       0.88      0.84      0.86       120
           4       1.00      0.98      0.99       120
           5       0.98      0.88      0.93       120

    accuracy                           0.93       720
   macro avg       0.93      0.93      0.93       720
weighted avg       0.93      0.93      0.93       720

0.9291666666666667
[[119   0   1   0   0   0]
 [  0 114   0   5   0   1]
 [  8   0 112   0   0   0]
 [  0  18   0 101   0   1]
 [  0   0   2   0 118   0]
 [  0   6   0   9   0 105]]
              precision    recall  f1-score   support

           0       0.94      0.99     

In [ ]:
# twin SVM

In [ ]:
# example SVM without kernel

clf = TwinSVMClassifier()
#clf = sklearn.multiclass.OneVsOneClassifier(clf) or sklearn.multiclass.OneVsRestClassifier(clf) depending on your needs
# Train the classifier
clf = clf.fit(X_train, y_train)

# Output prediction
yhat = clf.predict(X_test)
print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

0.3333333333333333
[[120   0   0   0   0   0]
 [  0 120   0   0   0   0]
 [117   3   0   0   0   0]
 [ 35  85   0   0   0   0]
 [ 44  76   0   0   0   0]
 [ 26  94   0   0   0   0]]
              precision    recall  f1-score   support

           0       0.35      1.00      0.52       120
           1       0.32      1.00      0.48       120
           2       0.00      0.00      0.00       120
           3       0.00      0.00      0.00       120
           4       0.00      0.00      0.00       120
           5       0.00      0.00      0.00       120

    accuracy                           0.33       720
   macro avg       0.11      0.33      0.17       720
weighted avg       0.11      0.33      0.17       720



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn import multiclass

In [ ]:
# clf = TwinSVMClassifier()
clf = multiclass.OneVsOneClassifier(clf) 
# Train the classifier
clf = clf.fit(X_train, y_train)

# Output prediction
yhat = clf.predict(X_test)
print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

0.8680555555555556
[[120   0   0   0   0   0]
 [  0 120   0   0   0   0]
 [ 10   0 102   0   4   4]
 [  0  35   0  82   3   0]
 [  0   0   0   0 120   0]
 [  0  19   0  20   0  81]]
              precision    recall  f1-score   support

           0       0.92      1.00      0.96       120
           1       0.69      1.00      0.82       120
           2       1.00      0.85      0.92       120
           3       0.80      0.68      0.74       120
           4       0.94      1.00      0.97       120
           5       0.95      0.68      0.79       120

    accuracy                           0.87       720
   macro avg       0.89      0.87      0.87       720
weighted avg       0.89      0.87      0.87       720



In [ ]:
# clf = TwinSVMClassifier()
clf = multiclass.OneVsRestClassifier(clf)
# Train the classifier
clf = clf.fit(X_train, y_train)

# Output prediction
yhat = clf.predict(X_test)
print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

0.8027777777777778
[[119   0   0   0   1   0]
 [  0 119   0   0   0   1]
 [ 17   0  91   0   6   6]
 [  1  51   0  25   8  35]
 [  0   0   0   0 120   0]
 [  0  16   0   0   0 104]]
              precision    recall  f1-score   support

           0       0.87      0.99      0.93       120
           1       0.64      0.99      0.78       120
           2       1.00      0.76      0.86       120
           3       1.00      0.21      0.34       120
           4       0.89      1.00      0.94       120
           5       0.71      0.87      0.78       120

    accuracy                           0.80       720
   macro avg       0.85      0.80      0.77       720
weighted avg       0.85      0.80      0.77       720



In [ ]:
# example SVM RBF kernel params with fuzzy membership function

clf = TwinSVMClassifier(0.1,0.1,1,1,3,2,1)
#clf = sklearn.multiclass.OneVsOneClassifier(clf) or sklearn.multiclass.OneVsRestClassifier(clf) depending on your needs
# Train the classifier
clf = clf.fit(X_train, y_train)

# Output prediction
yhat = clf.predict(X_test)
print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

0.28888888888888886
[[120   0   0   0   0   0]
 [ 32  88   0   0   0   0]
 [120   0   0   0   0   0]
 [119   1   0   0   0   0]
 [120   0   0   0   0   0]
 [120   0   0   0   0   0]]
              precision    recall  f1-score   support

           0       0.19      1.00      0.32       120
           1       0.99      0.73      0.84       120
           2       0.00      0.00      0.00       120
           3       0.00      0.00      0.00       120
           4       0.00      0.00      0.00       120
           5       0.00      0.00      0.00       120

    accuracy                           0.29       720
   macro avg       0.20      0.29      0.19       720
weighted avg       0.20      0.29      0.19       720



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# example SVM linear kernel params with fuzzy membership function

clf = TwinSVMClassifier(0.1,0.1,1,1,1,2,1)
#clf = sklearn.multiclass.OneVsOneClassifier(clf) or sklearn.multiclass.OneVsRestClassifier(clf) depending on your needs
# Train the classifier
clf = clf.fit(X_train, y_train)

# Output prediction
yhat = clf.predict(X_test)
print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

LinAlgError: ignored

In [ ]:
# example SVM polynomial kernel params with fuzzy membership function

clf = TwinSVMClassifier(0.1,0.1,1,1,2,2,1)
#clf = sklearn.multiclass.OneVsOneClassifier(clf) or sklearn.multiclass.OneVsRestClassifier(clf) depending on your needs
# Train the classifier
clf = clf.fit(X_train, y_train)

# Output prediction
yhat = clf.predict(X_test)
print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

LinAlgError: ignored

In [ ]:
clf = TwinSVMClassifier(0.1,0.1,1,1,3,2,0)
#clf = sklearn.multiclass.OneVsOneClassifier(clf) or sklearn.multiclass.OneVsRestClassifier(clf) depending on your needs
# Train the classifier
clf = clf.fit(X_train, y_train)

# Output prediction
yhat = clf.predict(X_test)
print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

LinAlgError: ignored

In [ ]:
# example SVM without kernel

clf = TwinSVMClassifier(0.1,0.1,1,1,0,1,0)
#clf = sklearn.multiclass.OneVsOneClassifier(clf) or sklearn.multiclass.OneVsRestClassifier(clf) depending on your needs
# Train the classifier
clf = clf.fit(X_train, y_train)

# Output prediction
yhat = clf.predict(X_test)
print(metrics.accuracy_score(y_test, yhat))
print(confusion_matrix(y_test, yhat))
print(classification_report(y_test, yhat))

0.3333333333333333
[[120   0   0   0   0   0]
 [  0 120   0   0   0   0]
 [117   3   0   0   0   0]
 [ 35  85   0   0   0   0]
 [ 39  81   0   0   0   0]
 [ 26  94   0   0   0   0]]
              precision    recall  f1-score   support

           0       0.36      1.00      0.53       120
           1       0.31      1.00      0.48       120
           2       0.00      0.00      0.00       120
           3       0.00      0.00      0.00       120
           4       0.00      0.00      0.00       120
           5       0.00      0.00      0.00       120

    accuracy                           0.33       720
   macro avg       0.11      0.33      0.17       720
weighted avg       0.11      0.33      0.17       720



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from libtsvm.preprocess import DataReader

ModuleNotFoundError: ignored

In [ ]:
!pip install libtwinsvm

     |████████████████████████████████| 2.3 MB 18.2 MB/s 
     |████████████████████████████████| 149 kB 21.2 MB/s 
     |████████████████████████████████| 8.3 MB 34.9 MB/s 
     |████████████████████████████████| 59.9 MB 95 kB/s 
     |████████████████████████████████| 338 kB 63.5 MB/s 
  Created wheel for numpydoc: filename=numpydoc-0.7.0-py3-none-any.whl size=20996 sha256=6d8a6479ee95c92942595c399f7dba5931029215903b348926090e6cb608b2fe
  Stored in directory: /root/.cache/pip/wheels/12/b6/0d/31010d207388dff9c2ad1baa9e3e7e03ca3d112ad46074bf32
Successfully built numpydoc


In [ ]:
from libtsvm.preprocess import DataReader
from libtsvm.estimators import LSTSVM
from libtsvm.mc_scheme import OneVsOneClassifier
from libtsvm.model_selection import Validator
from libtsvm.estimators import TSVM

In [ ]:
# Step 2: Choose a TSVM-based estimator
kernel = 'RBF'
lstsvm_clf = LSTSVM(kernel=kernel)

# Step 3: Select a multi-class approach
ovo_lstsvm = OneVsOneClassifier(lstsvm_clf)


In [ ]:
print(len(x_new))
print(len(y_new))

3600
3600


In [ ]:
# Step 4: Evaluate the multi-class estimator using train/test split
eval_method = 't_t_split' # Train/Test split
test_set_size = 20 # 20% of samples

val = Validator(x_new, y_new, (eval_method, test_set_size), ovo_lstsvm)
eval_func = val.choose_validator()

In [ ]:
# Hyper-parameters of the classifier
h_params =  {'C1': 2**-2, 'C2': 2**-2, 'gamma': 2**-7}

acc, std, full_report = eval_func(h_params)

print("Accuracy: %.2f" % acc)
print(full_report)

/usr/local/lib/python3.7/dist-packages/libtsvm/estimators.py:572: RuntimeWarning: overflow encountered in exp
  return np.exp(-2 * u) * np.exp(2 * u * np.dot(x, y))
/usr/local/lib/python3.7/dist-packages/libtsvm/estimators.py:405: RuntimeWarning: overflow encountered in multiply
  inv_p_1 = np.linalg.inv((mat_G_G_t + (1 / self.C1) * mat_H_H_t) \
/usr/local/lib/python3.7/dist-packages/libtsvm/estimators.py:413: RuntimeWarning: overflow encountered in multiply
  inv_p_2 = np.linalg.inv((mat_H_H_t + (1 / self.C2) * mat_G_G_t) \


Accuracy: 15.00
{'accuracy': 15.0, 'acc_std': 0.0, 'micro_recall': 15.0, 'm_rec_std': 0.0, 'micro_precision': 15.0, 'm_prec_std': 0.0, 'mirco_f1': 15.0, 'm_f1_std': 0.0, 'C1': 0.25, 'C2': 0.25, 'gamma': 0.0078125}


/usr/local/lib/python3.7/dist-packages/libtsvm/estimators.py:572: RuntimeWarning: overflow encountered in exp
  return np.exp(-2 * u) * np.exp(2 * u * np.dot(x, y))


In [ ]:
# Step 2: Choose a TSVM-based estimator
kernel = 'linear'
tsvm_clf = TSVM(kernel=kernel)

# Step 3: Evaluate the estimator using cross validation
eval_method = 'CV' # Cross validation
folds = 5

val = Validator(x_new, y_new, (eval_method, folds), tsvm_clf)
eval_func = val.choose_validator()

# Hyper-parameters of the classifier
h_params =  {'C1': 2**-2, 'C2': 2**1}

acc, std, full_report = eval_func(h_params)

print("Accuracy: %.2f" % acc)
print(full_report)